version: '3.1'
services:
  db:
    image: mysql
    container_name: place_ti_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - place_ti_data:/var/lib/mysql

volumes:
  place_ti_data: